// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF停车场.Server.EFCore;

namespace WPF停车场.Server.EFCore.Migrations
{
    [DbContext(typeof(EFCoreContext))]
    [Migration("20230531115906_v1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("WPF.SmartParking.Server.Models.SysUserInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id");

                    b.Property<string>("PassWord")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("UseName")
                        .HasColumnType("text")
                        .HasColumnName("use_name");

                    b.HasKey("ID");

                    b.ToTable("sys_user_info");
                });
#pragma warning restore 612, 618
        }
    }
}
